name: Build Lesebriller for various operating systems

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with: 
                go-version: "1.23.2"
            - name: Install dependencies
              run: go get .
            - name: Build project
              run: go build -o lesebriller-${{ github.sha }}-${{ matrix.os }} -v .
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: lesebriller-${{ github.sha }}-${{ matrix.os }}
                path: lesebriller-${{ github.sha }}-${{ matrix.os }}