name: Run Go testing and upload results as an Artifact

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with: 
                go-version: "1.23.2" # I think it would be nice to make it automatically match the go.mod minimum in the future, but that might be a waste of time
            - name: Install dependencies
              run: go get .
            - name: Test with Go
              run: go test -json > TestResults-${{ github.sha }}.json
            - name: Upload Go test results
              uses: actions/upload-artifact@v4
              with:
                name: TestResults-${{ github.sha }}
                path: TestResults-${{ github.sha}}.json
